<?xml version="1.0" encoding="utf-8" ?>
	<!DOCTYPE TesterList [
		<!ELEMENT TestsList (Test)*>
		<!ELEMENT Test (TestClassName, WhatTest, HowWorkTest, WhenTestPass, Argument*)>
		<!ATTLIST Test 
	    	name     CDATA    #REQUIRED
	    	skip     CDATA    #REQUIRED
		>
		<!ELEMENT WhatTest (#PCDATA)*>
		<!ELEMENT HowWorkTest (#PCDATA)*>
		<!ELEMENT WhenTestPass (#PCDATA)*>
		<!ELEMENT Argument (#PCDATA)*>
		<!ATTLIST Argument
			key      CDATA    #REQUIRED
			value    CDATA    #REQUIRED
		>
	]>
<TestsList>
	<Test name="Pallete is almost empty" skip="false">
		<TestClassName>pallete.tests.PalleteAlmostEmptyTest</TestClassName>
		<WhatTest>"Tests whether a Pallete replies with the right message if
			it is almost empty (1-4 Blocks)"</WhatTest>
		<HowWorkTest></HowWorkTest>
		<WhenTestPass>"Passes if Pallete replies with 'almost_empty'"</WhenTestPass>
	</Test>
	<Test name="Pallete is empty" skip="false">
		<TestClassName>pallete.tests.PalleteEmptyTest</TestClassName>
		<WhatTest>"Tests whether a Pallete replies with the right message if
			it is empty (0 Blocks)"</WhatTest>
		<HowWorkTest></HowWorkTest>
		<WhenTestPass>"Passes if Pallete replies with 'empty'"</WhenTestPass>
	</Test>
	<Test name="Pallete is not empty anymore" skip="false">
		<TestClassName>pallete.tests.PalleteNotEmptyAnymoreTest</TestClassName>
		<WhatTest>"Tests whether a Pallete replies with the right message if
			it is not empty anymore(5 Blocks)"</WhatTest>
		<HowWorkTest></HowWorkTest>
		<WhenTestPass>"Passes if Pallete replies with 'not_empty_anymore"</WhenTestPass>
	</Test>
</TestsList>